pipeline_name: nodepred
device: 'cpu'
# Data configurations
data:
    name: PubmedGraphDataset
    data_dir: "/data/"
# Model configurations
model:
    name: GCN                      # Model name
    num_layers: 2                  # number of layers
    norm: both                # normalization for adjacency matrix, can be none, symmetric, right
    hidden_size: 16                # hidden layer size
    activation: relu               # activation
    dropout: 0.5                   # dropout
    use_edge_weight: False         # use edge weight or not
# Training configurations
general_pipeline:
    node_embed_size: -1
    early_stop: 
        checkpoint_path: 'checkpoint.pt'   # Checkpoint path
        patience: 20                       # Early stop patience
    num_epochs: 200                    # Number of training epochs
    eval_period: 5                     # Number of epochs between two evaluations
    optimizer:
        name: Adam                     # Optimizer name, can be Adam, ?
        lr: 0.005                      # Learning rate
        weight_decay: 0                # Weight decay
    loss: CrossEntropyLoss
